spring:
  application:
    name: livraria-api
  datasource:
    url: jdbc:postgresql://localhost:5432/livraria
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update