spring:
  application:
    name: livraria-api
  datasource:
    url: jdbc:postgresql://localhost:5432/livraria
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      #update: cria o banco e quando derrubar a aplicação o banco continua lá, fora que também persiste em caso de alterações
      #none: padrão (não faz nada)
      #create-drop: quando subir a aplicação cria tudo, mas quando derrubar ele irá dropar (é um banco por sessão) ideal para testes